version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=packs.db
    depends_on:
      - db
    networks:
      - app-network

  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: sqlite:latest
    volumes:
      - db-data:/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge